CREATE TABLE IF NOT EXISTS uploads (
    id SERIAL PRIMARY KEY,
    filename TEXT UNIQUE NOT NULL,
    size BIGINT NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'in-progress',
    md5 TEXT,
    sha256 TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
